# PRODUCER SERVER PORT
server:
  port: 8083


# ARTEMIS ACTIVEMQ CONFIGURATION
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: adminpass
    packages:
      trust-all: true
  artemis:
    embedded:
      queues: messages